"""agregar salones, franjas_clase, trimestres, horarios; quitar instructor_id de fichas; agregar ficha_id a usuarios

Revision ID: 211a6d970a40
Revises: f2b2d5b7e84b
Create Date: 2026-08-12 03:40:33.865388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211a6d970a40'
down_revision: Union[str, Sequence[str], None] = 'f2b2d5b7e84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###